import sqlite3
from datetime import datetime
import os
from dotenv import load_dotenv

# Load .env for DB path
load_dotenv()

DB_PATH = os.path.join(os.path.dirname(__file__), "../database/osint_threats.db")

def seed_fake_threat():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Create threat with a random ID based on timestamp
    threat_id = int(datetime.now().timestamp())
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    cursor.execute("""
        INSERT INTO threats (id, source, threat_type, indicator, description, date_detected, confidence, extra_info)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?);
    """, (
        threat_id,
        "seed_script",
        "phishing",
        f"test{threat_id}.com",
        "Fake threat inserted for testing Telegram alerts",
        now,
        "High",
        "Generated by seed_fake_threat.py"
    ))

    conn.commit()
    conn.close()

    print(f"[+] Inserted fake threat with ID {threat_id}")

if __name__ == "__main__":
    seed_fake_threat()
